name: Build Unsigned APK

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build unsigned APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Find unsigned APK
        id: find_apk
        run: |
          APK_PATH=$(find $GITHUB_WORKSPACE/app/build/outputs/apk/debug -name "*.apk" | grep -v signed | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Upload unsigned APK
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-apk
          path: ${{ steps.find_apk.outputs.apk_path }}
          if-no-files-found: error
